name: Python Linting

on: [push]

jobs:
  lint:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v5
    - name: Set up Python
      run: uv python install
    - name: Install the project
      run: uv sync --locked --all-extras --dev
    - name: Lint with Ruff
      run: uv run ruff check .
    - name: Type check with Mypy
      run: uv run mypy .
