name: Python Linting

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install uv
      run: curl -LsSf https://astral.sh/uv/install.sh | sh
    - name: Install dependencies
      run: |
        $HOME/.cargo/bin/uv sync
    - name: Lint with Ruff
      run: $HOME/.cargo/bin/uv run ruff check .
    - name: Type check with Mypy
      run: $HOME/.cargo/bin/uv run mypy .
